# Generated by Django 4.1.3 on 2023-01-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
